testing functionality
CasoMateo/Nursing-Home pull request #2
Opened 2022-05-01 15:33 UTC by CasoMateo

Checking final authentication details

2022-05-02 06:51 UTC, EduardoSantos7 requested changes
Do not upload .pyc  files

2022-05-02 06:51 UTC, EduardoSantos7 commented on backend/server.py
> +  "http://localhost:3000"
This won't let you deploy your code in any cloud or between networks, be aware and think about which type of deployment you will do.

2022-05-02 06:51 UTC, EduardoSantos7 commented on backend/server.py
> +cluster = MongoClient()
Now you are don't have aconnection to the DB, please use environment variables '.env' file, if you have doubts about it let me know in class

2022-05-02 06:51 UTC, EduardoSantos7 commented on backend/server.py
> +def getCookie(cname, ccookies):
Add test for all this functions

2022-05-02 06:51 UTC, EduardoSantos7 commented on backend/server.py
> +  if not user['level']:
use get to avoid key error or pre-check for the key

2022-05-02 06:51 UTC, EduardoSantos7 commented on backend/server.py
> +    usernames.append(user['username'])
same here try to avoid key errors

2022-05-02 06:51 UTC, EduardoSantos7 commented on backend/server.py
> +      if medicine['badges'][badge]['date'] == attributes.expiry:
don't use multiple direct accesses

2022-05-02 06:51 UTC, EduardoSantos7 commented on backend/server.py
> +      if medicine['badges'][badge]['date'] == attributes.expiry and medicine['badges'][badge]['quantity'] >= attributes.quantity:
same here

2022-05-02 06:51 UTC, EduardoSantos7 commented on frontend/src/components/Home.jsx
> +      let c = ca[i];
please use explicit names (c is not one)

2022-05-11 22:17 UTC, CasoMateo commented on backend/server.py
> +def getCookie(cname, ccookies):
Added a separate tests file with all of these

2022-05-16 01:08 UTC, merged